### PR TITLE
Vaishnavi Pasumarthi ML Zip add

### PR DESCRIPTION
**Pull request by vaipos**
### Vaishnavi Pasumarthi
Open sourcing ML Specialization Personal work  

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).
Vaishnavi Pasumarthi

### CODE REVIEW

**Comment by dhrubo-os** [comment]
What exactly the goal of this PR? Which issue are you working on? Can you please describe elaborately?

**Comment by vaipos** [comment]
@dhrubo-os I was requested by @ylwu-amzn to put my ML portfolio work into this repository instead of ml-commons as it consists mainly of py files. I am currently experimenting and will be working on putting in a valuable PR! 😊

**Comment by rawwar** [comment]
If this isn't ready to be reviewed, can this be converted to a draft PR? @vaipos

**Comment by vaipos** [comment]
Oh yes, you can close the PR

**Pull request closed without merging**
