### PR TITLE
Bumping pandas version from 1.5.0 to 2.x

### PR DESCRIPTION
**Pull request by Yerzhaisang**
### Description
Fix all issues when pandas is upgraded from 1.5.0 to 2.x
 
### Issues Resolved
https://github.com/opensearch-project/opensearch-py-ml/issues/270
 
### Check List
- [x] New functionality includes testing.
  - [x] All tests pass
- [ ] New functionality has been documented.
  - [ ] New functionality has javadoc added
- [x] Commits are signed per the DCO using --signoff 

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

### CODE REVIEW

**Comment by Yerzhaisang** [comment]
Dear @dhrubo-os, this is just draft PR. I replaced deprecated mad method in pandas 2.x.x with custom function for now.
I continue to fix other deprecated methods in pandas 2.x.x

**Comment by dhrubo-os** [comment]
Let's take all the updates from main.

**Comment by dhrubo-os** [comment]
looks like integration tests are failing.

**Comment by Yerzhaisang** [comment]
> looks like integration tests are failing.

Yeah, I will let you know when it's fixed

**Comment by dhrubo-os** [comment]
@Yerzhaisang are you still working on this issue?

**Pull request closed without merging**
